autoCorrect: true
failFast: true

style:
  MaxLineLength:
    maxLineLength: 100
  UnusedPrivateMember:
    active: false
  WildcardImport:
    active: false
  UnnecessaryAbstractClass:
    active: false
  ForbiddenComment:
    active: false
  ExpressionBodySyntax:
    active: false
  MandatoryBracesIfStatements:
    active: false
  DataClassContainsFunctions:
    active: false

comments:
  active: false

complexity:
  LabeledExpression:
    active: false
  TooManyFunctions:
    active: false

potential-bugs:
  UnsafeCast:
    active: false
  LateinitUsage:
    active: false
